POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "superadmin1@snacktopia.co",
  "password": "superadmin1"
}

###

POST http://localhost:4000/api/orders
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwOXJpOWxzZnl4eTRrNGp1cTludzJqcGEiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzQzNjQ0MTU5LCJleHAiOjE3NDM2NDQ3NTl9.vyY35brq3nt2uFKfiY8dx5dl1RsG0fxMhvoqUe73wIU; refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwOXJpOWxzZnl4eTRrNGp1cTludzJqcGEiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc0MzY0NDE1OSwiZXhwIjoxNzQ0MjQ4OTU5fQ.VrTGgJK0DBsT0r6N3gmGdmA35yU5o_qFcZE2_S0ibJw

{
  "items": [
    {
      "productId": "a3lhkbvzo8868yot73ofqu3s",
      "quantity": 10
    }
  ]
}
###
POST http://localhost:4000/api/carts/1/items
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwOXJpOWxzZnl4eTRrNGp1cTludzJqcGEiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzQzNjQ0MTU5LCJleHAiOjE3NDM2NDQ3NTl9.vyY35brq3nt2uFKfiY8dx5dl1RsG0fxMhvoqUe73wIU; refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwOXJpOWxzZnl4eTRrNGp1cTludzJqcGEiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc0MzY0NDE1OSwiZXhwIjoxNzQ0MjQ4OTU5fQ.VrTGgJK0DBsT0r6N3gmGdmA35yU5o_qFcZE2_S0ibJw


{
  "productId": "a3lhkbvzo8868yot73ofqu3s"
}

###
GET http://localhost:4000/api/carts/1/items
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwOXJpOWxzZnl4eTRrNGp1cTludzJqcGEiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzQzNjQ0MTU5LCJleHAiOjE3NDM2NDQ3NTl9.vyY35brq3nt2uFKfiY8dx5dl1RsG0fxMhvoqUe73wIU; refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwOXJpOWxzZnl4eTRrNGp1cTludzJqcGEiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc0MzY0NDE1OSwiZXhwIjoxNzQ0MjQ4OTU5fQ.VrTGgJK0DBsT0r6N3gmGdmA35yU5o_qFcZE2_S0ibJw


###
PATCH http://localhost:4000/api/carts/1/items/qvv7ulnne16ite36khtih3q7
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwOXJpOWxzZnl4eTRrNGp1cTludzJqcGEiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzQzNjQ0MTU5LCJleHAiOjE3NDM2NDQ3NTl9.vyY35brq3nt2uFKfiY8dx5dl1RsG0fxMhvoqUe73wIU; refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwOXJpOWxzZnl4eTRrNGp1cTludzJqcGEiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc0MzY0NDE1OSwiZXhwIjoxNzQ0MjQ4OTU5fQ.VrTGgJK0DBsT0r6N3gmGdmA35yU5o_qFcZE2_S0ibJw


{
  "quantity": 1
}

###
DELETE http://localhost:4000/api/carts/1/items
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwOXJpOWxzZnl4eTRrNGp1cTludzJqcGEiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzQzNjQ0MTU5LCJleHAiOjE3NDM2NDQ3NTl9.vyY35brq3nt2uFKfiY8dx5dl1RsG0fxMhvoqUe73wIU; refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwOXJpOWxzZnl4eTRrNGp1cTludzJqcGEiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc0MzY0NDE1OSwiZXhwIjoxNzQ0MjQ4OTU5fQ.VrTGgJK0DBsT0r6N3gmGdmA35yU5o_qFcZE2_S0ibJw


{
  "itemIds": ["a3lhkbvzo8868yot73ofqu3s"]
}