export const products = [
  {
    id: 'bslc0a924ppvzrod5suwurzq',
    categoryId: 'cf2pr8ygr0ouvna9nbq506je',
    name: '허니버터칩',
    price: 1500,
    description: '달콤한 허니버터 맛이 일품인 과자',
    imageUrl: 'https://placehold.co/600x400?text=honeybutter',
  },
  {
    id: 'jlvtn4vc0wkycxa9c9koa2sw',
    categoryId: 'iuo1on0s7inc2kx5r0gelzex',
    name: '콜라',
    price: 2000,
    description: '시원한 탄산음료',
    imageUrl: 'https://placehold.co/600x400?text=cola',
  },
  {
    id: 'yekzmqb5gabo5q0l9zpj5lsb',
    categoryId: 'oajyhulxfi066y751yhw1iuk',
    name: '삼다수 2L',
    price: 1200,
    description: '제주 화산암반수로 만든 생수',
    imageUrl: 'https://placehold.co/600x400?text=water',
  },
  {
    id: 'cgztlfcf18nlufpq7fjtp3on',
    categoryId: 'w329r2phpcsn1emwzb4yux62',
    name: '신라면 컵',
    price: 1300,
    description: '매콤한 국물이 일품인 컵라면',
    imageUrl: 'https://placehold.co/600x400?text=cup+noodle',
  },
  {
    id: 'ylwf20woxv501edrmb39icdj',
    categoryId: 'ote70z85578gzvmbomh0whkh',
    name: '닭가슴살 샐러드',
    price: 6500,
    description: '신선한 채소와 닭가슴살이 들어간 건강한 샐러드',
    imageUrl: 'https://placehold.co/600x400?text=salad',
  },
  {
    id: 'f6gf7ghekzui2aleo4bgpbuu',
    categoryId: 'wdek4b93hbzaqk0wid4ql0zn',
    name: '에티오피아 예가체프',
    price: 25000,
    description: '꽃향이 풍부한 에티오피아 원두',
    imageUrl: 'https://placehold.co/600x400?text=coffee+bean',
  },
  {
    id: 'c7bsuomxn2shkkdagy2tgk4o',
    categoryId: 'b1edqeyeb295wrykbidtce6p',
    name: '종이컵 6.5oz (50개입)',
    price: 3000,
    description: '무형광 친환경 종이컵',
    imageUrl: 'https://placehold.co/600x400?text=paper+cup',
  },
  {
    id: 'loxjyu4pah08srxk0htl0rfw',
    categoryId: 'mp4abgflpsnaswnscmuyfbjn',
    name: '제주 감귤 1kg',
    price: 8900,
    description: '새콤달콤한 제주 감귤',
    imageUrl: 'https://placehold.co/600x400?text=tangerine',
  },
  {
    id: 'eptso4pwypawjizueiec0ont',
    categoryId: 'o4krp07hbz55ofit3t9152f7',
    name: '다크초콜릿 70%',
    price: 4500,
    description: '카카오 함량 70%의 프리미엄 다크초콜릿',
    imageUrl: 'https://placehold.co/600x400?text=chocolate',
  },
  {
    id: 'wpp6zwl7t8962v3g30gvprhq',
    categoryId: 'z9hgjsi0nbp0qodu2tmyi4lh',
    name: '캐모마일 티백 20개입',
    price: 5500,
    description: '릴렉싱에 도움을 주는 캐모마일차',
    imageUrl: 'https://placehold.co/600x400?text=chamomile',
  },
];

// import cuid2 from '@paralleldrive/cuid2';
// const arr = Array.from({ length: 6 }, x => cuid2.createId());
// console.log(arr);
