#!/bin/sh

# CI 환경 체크
is_ci_environment() {
  [ -n "$CI" ] || [ -n "$GITHUB_ACTIONS" ]
}

# CI 환경에서는 hook 스킵
if is_ci_environment; then
  exit 0
fi

# pnpm이 설치되어 있으면 1, 설치되어 있지 않으면 0을 반환한다
PNPM_INSTALLED=$(pnpm -v > /dev/null 2>&1; echo $?)

if [ "$PNPM_INSTALLED" -ne 0 ]; then
  printf "\033[31m❌ pnpm이 설치되어 있지 않습니다. pnpm을 설치해주세요.\033[0m\n"
  exit 1
fi

pnpm dlx commitlint --edit "$1"